name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cd .. && cmake HelloCMake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=./dist
    - name: build and install
      run: cmake --build build && cmake --install build
    - name: run main application
      run: ./dist/bin/main
    - name: run test via ctest
      run: cd build && ctest
